#!/bin/bash

# Function definition

# The "Virtual" function for ask_normal and ask_hidden
# $1: n, for normal, and h for hidden. It means if the ask is outputed or not.
# $2: The string that will be evaluated
# $3: The question title
# $4: The variable name
# $5: The error message when blank is provided. If $3 is not, blank answer is allowed.
ask_mysql() {
    if [ $1 = n ]; then
        read -p "$2" $3
    elif [ $1 = h ]; then
        read -s -p "$2" $3
    fi

    var_value=${!3}
    message_when_blank=$4

    if [ ! ${#message_when_blank} -eq 0 ]; then 
        if [ ${#var_value} -eq 0 ]; then
            echo $message_when_blank
            ask_mysql $1 "$2" $3 "$4"
        fi
    fi
}

# $1: The question title
# $2: The variable name
# $3: The error message when blank is provided. If $3 is not, blank answer is allowed.
ask_mysql_normal() {
    execute='read -p'
    ask_mysql $execute $1 $2 $3
}

# $1: The question title
# $2: The variable name
# $3: The error message when blank is provided. If $3 is not, blank answer is allowed.
ask_mysql_hidden() {
    execute='read -s -p'
    ask_mysql $execute $1 $2 $3
}


# Actions

ask_mysql n "1:5 -> Please, provides the database user: " mysql_user "You did not provides anything for mysql user!"
ask_mysql n "2:5 -> Please, provides the database name: " mysql_databasename "You did not provides anything for mysql database name!"
ask_mysql h "3:5 -> Please, provides the database password: " mysql_databasepassword
echo ""
ask_mysql n "4:5 -> Please, provides the database host: " mysql_host "You did not provides anything to database host."
ask_mysql n "5:5 -> Please, provides the database prefix, if required: " mysql_prefix

echo $mysql_user
echo $mysql_databasename
echo $mysql_databasepassword
echo $mysql_host
echo $mysql_prefix